repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: isort
        exclude: (__init__.py)
        language: system
        types: [ python ]
