from .keyboards import KEYBOARDS, FWD_STR, BCK_STR, UP_STR, FIN_STR, ORG_STR, OTH_STR, TECH_STR, ACC_STR, FIN_Q1_STR, \
    FIN_Q2_STR, FIN_Q3_STR, FIN_Q4_STR, FIN_Q5_STR, ORG_Q1_STR, OTH_Q1_STR, TECH_Q1_STR, TECH_Q2_STR, TECH_Q3_STR, \
    ACC_Q1_STR, ACC_Q2_STR
